/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_peluqueria;

import conexion.conexionBD;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author JESÚS
 */
public class Crear extends javax.swing.JPanel  {
private conexionBD conexion = new conexionBD();
   
    /**
     * Creates new form Crear
     */
    public Crear() {
        initComponents();
        setLocation(145, 270);
        conexion.conectar();
       
        //setBounds(200, 100, 100, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        Olvidar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(242, 242, 238));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Usuario");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Contraseña");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Repetir Contraseña");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("Clave");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jTextField1.setBackground(new java.awt.Color(242, 242, 238));
        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField1.setText("Correo@gmail.com");
        jTextField1.setBorder(null);
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 110, 20));

        jTextField4.setBackground(new java.awt.Color(242, 242, 238));
        jTextField4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jTextField4.setText("Ingrese su usuario");
        jTextField4.setBorder(null);
        jTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField4FocusGained(evt);
            }
        });
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 110, 20));

        Olvidar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.png"))); // NOI18N
        Olvidar.setBorderPainted(false);
        Olvidar.setContentAreaFilled(false);
        Olvidar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Olvidar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar_Oscuro.png"))); // NOI18N
        Olvidar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Refrescar_Oscuro.png"))); // NOI18N
        Olvidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OlvidarActionPerformed(evt);
            }
        });
        add(Olvidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/enviar - copia.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EnviarOScuro.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EnviarOScuro.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(242, 242, 238));
        jPasswordField1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPasswordField1.setText("vdasdadadasd");
        jPasswordField1.setBorder(null);
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusGained(evt);
            }
        });
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 110, 20));

        jPasswordField2.setBackground(new java.awt.Color(242, 242, 238));
        jPasswordField2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jPasswordField2.setText("fafasfqwewqg");
        jPasswordField2.setBorder(null);
        jPasswordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField2FocusGained(evt);
            }
        });
        add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 110, 20));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 110, 10));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 110, 10));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 110, 10));

        jSeparator8.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 110, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void OlvidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OlvidarActionPerformed
    Principal p = new Principal();
        p.show();
    ((JFrame)SwingUtilities.getWindowAncestor(this)).dispose();
    }//GEN-LAST:event_OlvidarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
        String usuario=jTextField4.getText();
       String contraseña=jPasswordField1.getText();
       String Repetir=jPasswordField2.getText();
       String Clave=jTextField1.getText();
       String sql="Insert into Login (usuario,contraseña,clave) VALUES ('"+usuario+"' , '"+contraseña+"' , '"+Clave+"') ";
       String sq="select usuario from login where usuario='"+usuario+"'";
        
       try{
           
        ResultSet res=conexion.getSentencia().executeQuery(sq);
           //filas=conexion.getSentencia().executeQuery(sq);
          if(res.next()){
               JOptionPane.showMessageDialog(jButton1,"Usuario Ya Existente", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
              
          }else if(contraseña.equals(Repetir)){
             conexion.getSentencia().executeUpdate(sql);
            JOptionPane.showMessageDialog(jButton1,"Usuario Creado", "GUARDADO", JOptionPane.INFORMATION_MESSAGE);
            jTextField4.setText("Ingrese su usuario");
            jTextField1.setText("Correo@gmail.com");
            jPasswordField1.setText("vdasdadadasd");
            jPasswordField2.setText("fafasfqwewqg");
        }else if(Clave.equals("") || Clave.equals(" ") || usuario.equals("") || usuario.equals(" ") || contraseña.equals(" ") || contraseña.equals("")){
               JOptionPane.showMessageDialog(jButton1,"Rellene Todos Los Campos Para Mas Seguridad", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
            else{
             
          JOptionPane.showMessageDialog(jButton1,"Contraseña Desiguales ", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
          }
                  
       }catch(SQLException s){
           System.out.println("ERROR" + s);
       }
       
               
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField4FocusGained
         String dato = jTextField4.getText();
        
        if(dato.equals("Ingrese su usuario")){
            jTextField4.setText("");
           
        }else{
            dato=jTextField4.getText();
           
        }
        
    }//GEN-LAST:event_jTextField4FocusGained

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
         String dato = jTextField1.getText();
        
        if(dato.equals("Correo@gmail.com")){
            jTextField1.setText("");
           
        }else{
            dato=jTextField1.getText();
           
        }
        
    }//GEN-LAST:event_jTextField1FocusGained

    private void jPasswordField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusGained
       String dato = jPasswordField1.getText();
        
        if(dato.equals("vdasdadadasd")){
            jPasswordField1.setText("");
           
        }else{
            dato=jPasswordField1.getText();
           
        }
        
    }//GEN-LAST:event_jPasswordField1FocusGained

    private void jPasswordField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField2FocusGained
      String dato = jPasswordField2.getText();
        
        if(dato.equals("fafasfqwewqg")){
            jPasswordField2.setText("");
           
        }else{
            dato=jPasswordField2.getText();
           
        }
    }//GEN-LAST:event_jPasswordField2FocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Olvidar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
